name: 'Doctl Helm Action'
description: 'This action manages the login to Digital Ocean and allows you to run a helm command'
inputs:
  cmd:
    description: 'The command that should be run'
    required: true
  working_directory:
    description: "This is where the helm command will be run from"
  number_of_retries:
    description: "This the number of attempts the system will use on"
    default: 3
  helm_timeout:
    description: "This is how many seconds to allow the helm process to run before killing it"
    default: 120
runs:
  using: 'docker'
  #image: 'Dockerfile'
  image: "docker://ghcr.io/r26d/doctl-helm-action/doctl-helm-action:v1.50.8"
  args:
    - ${{ inputs.cmd }}
    - ${{ inputs.working_directory }}
    - ${{ inputs.helm_timeout }}
    - ${{ inputs.number_of_retries }}