name: 'Doctl Helm Action'
description: 'This action manages the login to Digital Ocean and allows you to run a helm command'
inputs:
  cmd:
    description: 'The command that should be run'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.cmd }}
