name: 'Doctl Helm Action'
description: 'This action manages the login to Digital Ocean and allows you to run a helm command'
inputs:
  cmd:
    description: 'The command that should be run'
    required: true
  working_dir:
    description: "This is where the helm command will be run from"
runs:
  using: 'docker'
  #image: 'Dockerfile'
  image: "docker://delmendo/doctl-helm-action:latest"
  args:
    - ${{ inputs.cmd }}
    - ${{ inputs.working_dir }}